spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:33061/hex_demo
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: 10
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      use_sql_comments: true
      hibernate:
        default_batch_fetch_size: 50
        show_sql: true
        format_sql: false
        globally_quoted_identifiers: true

infra:
  kafka:
    bootstrap-server: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: PLAINTEXT
        acks: all
        retries: 3
        compression-type: gzip
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        auto-offset-reset: earliest
        security.protocol: PLAINTEXT
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
